Root: {
    path = "/src";
}

Extension: {
    type = ".js";
}

Directories: {
    controllers = "/main/java/com/example/springcsr/controllers";
    models = "/main/java/com/example/springcsr/models";
    repositories = "/main/java/com/example/springcsr/repositories";
    services = "/main/java/com/example/springcsr/services";
}
