Root: {
    path = "/src";
}

Extension: {
    type = ".java";
}

Directories: {
    controllers = "main/java/com/example/springssr/controllers";
    models = "main/java/com/example/springssr/models";
    repositories = "main/java/com/example/springssr/repositories";
    services = "main/java/com/example/springssr/services";
    templates  = "main/resources/templates";
}

Files: {
    controllers = "Controller";
    models = "Model";
    repositories = "Repository";
    services = "Service";
    templates = "Template"
}