Root: {
    path = "";
}

Extension: {
    type = ".cs";
}

Directories: {
    controllers = "Controllers";
    models = "Models";
    views = "Views";
}

Files: {
    controllers = "Controller";
    models = "Model";
    views = "View"
}
